/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e6d427510a37502b05b092f
*
* You will get 10% discount for each one of your friends
* 
*/
import React, { Component } from "react";
import { Link } from "react-router-dom";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Custom Actions
import UserActions from '../redux/actions/UserActions';

// START IMPORT ACTIONS

// END IMPORT ACTIONS

/** APIs

**/

class Home extends Component {
  render() {
    return (
      <div className="home-page">
        <h2>StringArt Proof of Concept</h2>
        <p>
          Esta PoC transforma uma imagem em uma representação vetorial de StringArt,
          permitindo configurar moldura, quantidade de pregos, espessura do fio e
          ajustes de realce para facilitar a visualização dos traços.
        </p>

        <h3>Experimente</h3>
        <p>
          Acesse o <Link to="/string-art">StringArt Studio</Link> para carregar uma imagem,
          gerar o mapa de bordas e visualizar o caminho sugerido das linhas.
        </p>

        <h3>O que está implementado</h3>
        <ul>
          <li>Conversão da imagem para tons de cinza com ajuste de brilho e contraste.</li>
          <li>Filtro Sobel simples para destacar contornos antes de gerar o vetor.</li>
          <li>Definição de molduras circulares, quadradas ou retangulares com número de pregos customizável.</li>
          <li>Geração de um caminho sequencial de linhas e visualização direta no canvas.</li>
        </ul>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsUser: bindActionCreators(UserActions, dispatch)
  };
};

// Validate types
Home.propTypes = {
  actionsUser: PropTypes.object.isRequired
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    user: state.LoginReducer.user
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Home);
